#cloud-config
# Cloud-init для bastion-хоста: SSH + kubectl

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTMwbmoXb3AuRGAgmlZhn3O7nV7mHhb7P7bXn7uhUUnmjBAtfufaWV/7wOA2Mt4TvbskmyyV6bIzm/0rjFOXErhZDABOriGuF8+BPq9QCb1vTRRRbRTotYPCu8JPd7akPkoT5RHxAbTXGVXi1ji1+eVVQBqTbZSl1JTR8DvCUg8OF87oYwQRz99f6e4XTBGrKxAq0m7p0+zzC/it6mecBJALKVeuGDCKMhLYQwn2cXAPK0wUg3Nu5q5YEPvSM4SJu6fNIy95DkWsACSPWcZu5fIDs5aNNH8jYNVhEmlvSmREkk+Jo4Y9Bc+LNNqPwbB5IzxmwKjx7Xk0tlUUA486ub mikhail@mikhail-Lenovo-ideapad-330-15IGM

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - ca-certificates
  - htop
  - net-tools

ssh_pwauth: false
disable_root: true

runcmd:
  - |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - |
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - |
    curl -sSL -o argocd "https://github.com/argoproj/argo-cd/releases/download/v2.13.3/argocd-linux-amd64"
  - |
    install -o root -g root -m 0755 argocd /usr/local/bin/argocd

timezone: Europe/Moscow

write_files:
  - path: /var/log/cloud-init-output.log
    permissions: '0644'
    owner: root:root
    content: |
      Cloud-init initialization completed
      Bastion host is ready for kubectl access

final_message: |
  Bastion-host готов. Можно использовать kubectl.
  Время инициализации: $UPTIME секунд

