#cloud-config
# Cloud-init скрипт для инициализации виртуальной машины momo-store в Yandex Cloud
# Настраивает SSH, базовое ПО и подготовку системы для веб-приложения momo-store

users:
  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      # - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC... user@host

# Обновление системы
package_update: true
package_upgrade: true

# Установка базовых пакетов
packages:
  - curl
  - wget
  - git
  - ufw
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - software-properties-common
  - htop
  - net-tools

# Настройка SSH
ssh_pwauth: false
disable_root: true

# Настройка firewall (UFW)
runcmd:
  # Разрешаем SSH
  - ufw allow 22/tcp comment 'SSH'
  # Разрешаем HTTP
  - ufw allow 80/tcp comment 'HTTP'
  # Разрешаем HTTPS
  - ufw allow 443/tcp comment 'HTTPS'
  # Включаем firewall с политикой deny по умолчанию
  - ufw --force enable
  # Создаем базовые директории для приложений momo-store
  - mkdir -p /opt/momo-store/backend
  - mkdir -p /opt/momo-store/frontend
  - mkdir -p /var/log/momo-store
  # Устанавливаем правильные права
  - chmod 755 /opt/momo-store
  - chmod 755 /var/log/momo-store

# Настройка времени
timezone: Europe/Moscow

# Запись логов cloud-init
write_files:
  - path: /var/log/cloud-init-output.log
    permissions: '0644'
    owner: root:root
    content: |
      Cloud-init initialization completed
      System ready for momo-store application deployment

# Финальное сообщение
final_message: |
  Cloud-init завершил инициализацию системы momo-store.
  Система готова к развертыванию приложения momo-store.
  Время инициализации: $UPTIME секунд

