#cloud-config

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTMwbmoXb3AuRGAgmlZhn3O7nV7mHhb7P7bXn7uhUUnmjBAtfufaWV/7wOA2Mt4TvbskmyyV6bIzm/0rjFOXErhZDABOriGuF8+BPq9QCb1vTRRRbRTotYPCu8JPd7akPkoT5RHxAbTXGVXi1ji1+eVVQBqTbZSl1JTR8DvCUg8OF87oYwQRz99f6e4XTBGrKxAq0m7p0+zzC/it6mecBJALKVeuGDCKMhLYQwn2cXAPK0wUg3Nu5q5YEPvSM4SJu6fNIy95DkWsACSPWcZu5fIDs5aNNH8jYNVhEmlvSmREkk+Jo4Y9Bc+LNNqPwbB5IzxmwKjx7Xk0tlUUA486ub mikhail@mikhail-Lenovo-ideapad-330-15IGM

# обновляем систему
package_update: true
package_upgrade: true

# устанавливаем нужные пакеты
packages:
  - curl
  - wget
  - git
  - ufw
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - software-properties-common
  - htop
  - net-tools

# настройка ssh
ssh_pwauth: false
disable_root: true

# часовой пояс
timezone: Europe/Moscow

# логи cloud-init
write_files:
  - path: /var/log/cloud-init-output.log
    permissions: '0644'
    owner: root:root
    content: |
      Cloud-init initialization completed
      System ready for application deployment

# финальное сообщение
final_message: |
  Cloud-init завершил инициализацию системы.
  Система готова к развертыванию приложений.
  Время инициализации: $UPTIME секунд

