# Пример CronJob для ежедневного дампа PostgreSQL и выгрузки в S3.
# Применить в namespace, где развёрнут PostgreSQL (или отдельный namespace backup).
# Перед применением: создать Secret backup-secrets с PGPASSWORD, S3_ACCESS_KEY, S3_SECRET_KEY
# и ConfigMap backup-config с PGHOST, PGDATABASE, S3_ENDPOINT, S3_BUCKET (или задать env ниже).
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-to-s3
  namespace: backup
spec:
  schedule: "0 2 * * *"   # каждый день в 02:00
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pg-dump
              image: postgres:15-alpine
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  apk add --no-cache gzip
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  DUMP_FILE="/tmp/pg_dump_${TIMESTAMP}.sql.gz"
                  pg_dump -h "${PGHOST}" -p "${PGPORT:-5432}" -U "${PGUSER}" -d "${PGDATABASE}" | gzip -c > "$DUMP_FILE"
                  if [ -n "$S3_ENDPOINT" ] && [ -n "$S3_BUCKET" ]; then
                    export AWS_ACCESS_KEY_ID="${S3_ACCESS_KEY}"; export AWS_SECRET_ACCESS_KEY="${S3_SECRET_KEY}"
                    apk add --no-cache aws-cli 2>/dev/null || true
                    aws s3 cp "$DUMP_FILE" "s3://${S3_BUCKET}/backups/postgres/${TIMESTAMP}.sql.gz" --endpoint-url "${S3_ENDPOINT}" || true
                  fi
                  rm -f "$DUMP_FILE"
                  echo "Backup completed ${TIMESTAMP}"
              envFrom:
                - secretRef:
                    name: backup-secrets
                - configMapRef:
                    name: backup-config
---
# Пример ConfigMap для параметров бэкапа (значения подставьте или создайте из values)
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: backup
data:
  PGHOST: "postgresql"
  PGPORT: "5432"
  PGUSER: "postgres"
  PGDATABASE: "app_store"
  S3_ENDPOINT: "https://storage.yandexcloud.net"
  S3_BUCKET: "my-backup-bucket"
---
# Secret backup-secrets создаётся вручную или через External Secrets (PGPASSWORD, S3_ACCESS_KEY, S3_SECRET_KEY)
# kubectl create secret generic backup-secrets -n backup --from-literal=PGPASSWORD=... --from-literal=S3_ACCESS_KEY=... --from-literal=S3_SECRET_KEY=...
