---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/part-of: momo-store
    env: "{{ .Values.environment }}"
data:
  vault_token: aHZzLm9HZFpIejB0RHNXNzljZTJPUTM1QnBOcw==
  mongodb_uri: bW9uZ29kYjovL3N0ZC1leHQtMDIxLTIxOlRlc3R1c3IxMjM0QHJjMWEtN3NrbHQwaWkzcG42dG1zNS5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC1leHQtMDIxLTIxP3Rscz10cnVlCg==
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: docker-config
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/part-of: momo-store
    env: "{{ .Values.environment }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImMzUmtMV1Y0ZEMwd01qRXRNakU2VW1JdFpWRkVaa0ZpVGpoVlFYTTJObWRWVkRRPSJ9fX0=
