# ClusterSecretStore для доступа к Yandex Lockbox (доступен из любого namespace).
# Требует: секрет {{ .Values.ycAuthSecretName }} с ключом {{ .Values.ycAuthSecretKey }} в namespace external-secrets.
{{- if .Values.lockboxSecretId }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: yandex-lockbox
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: {{ .Values.ycAuthSecretName }}
          key: {{ .Values.ycAuthSecretKey }}
          namespace: external-secrets
      apiEndpoint: lockbox.api.cloud.yandex.net
{{- end }}
